#!/usr/bin/nft -f
# vim:set ts=2 sw=2 et:

# IPv4/IPv6 Simple & Safe firewall ruleset.
# More examples in /usr/share/nftables/ and /usr/share/doc/nftables/examples/.

destroy table inet filter
table inet filter {
  chain input {
    type filter hook input priority filter
    policy drop

    ct state invalid drop comment "early drop of invalid connections"
    ct state {established, related} accept comment "allow tracked connections"
    iif lo accept comment "allow from loopback"
    meta l4proto { icmp, icmpv6 } accept comment "allow icmp"
    tcp dport ssh accept comment "allow sshd"
    #pkttype host limit rate 5/second counter reject with icmpx type admin-prohibited
    counter
    # Allow libvirt bridges BEFORE policy drop
    iifname "virbr*" accept comment "Allow libvirt networks"
    oifname "virbr*" accept comment "Allow libvirt networks" 
    iifname "virbr*" oifname "virbr*" accept comment "Allow libvirt forwarding"
    ip saddr 192.168.122.0/24 accept comment "Allow default libvirt NAT"
    ip daddr 192.168.122.0/24 ct state established,related accept
  }
  chain forward {
    type filter hook forward priority filter
    policy drop
    iifname "virbr*" oifname "virbr*" accept
    ct state established,related accept
  }
}
